/**
 * File: NewProject.java
 * Author: Steven Phung
 * Class: CECS-543-01 - Advanced Software Engineering
 * 
 * Assignment: Semester Project v.1.0
 * Date last modified: 2/24/2021
 * 
 * Purpose: This is the class that creates New Project dialog.
 */
package cecs_543_semester_project;

import javax.swing.tree.DefaultMutableTreeNode;

public class NewProject extends javax.swing.JFrame {
    
    //Parent class
    private MainFrame mainFrame;
    
    //Constructor
    public NewProject(MainFrame mainFrame) {
        initComponents();
        this.setTitle("New Project");
        this.setResizable(false);
        this.setVisible(true);
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_NewProject = new javax.swing.JPanel();
        label_Title = new javax.swing.JLabel();
        label_ProjectName = new javax.swing.JLabel();
        label_ProductName = new javax.swing.JLabel();
        label_CreatorName = new javax.swing.JLabel();
        label_Comments = new javax.swing.JLabel();
        button_OK = new javax.swing.JButton();
        button_Cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane_Comments = new javax.swing.JTextPane();
        textField_ProjectName = new javax.swing.JTextField();
        textField_ProductName = new javax.swing.JTextField();
        textField_CreatorName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Title.setText("CECS 543 Metrics Suite New Project");

        label_ProjectName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_ProjectName.setText("Project Name:");

        label_ProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_ProductName.setText("Product Name:");

        label_CreatorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_CreatorName.setText("Creator:");

        label_Comments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Comments.setText("Comments:");

        button_OK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_OK.setText("OK");
        button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_OKMouseClicked(evt);
            }
        });

        button_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_Cancel.setText("Cancel");
        button_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_CancelMouseClicked(evt);
            }
        });

        textPane_Comments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(textPane_Comments);

        textField_ProjectName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        textField_ProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        textField_CreatorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_NewProjectLayout = new javax.swing.GroupLayout(panel_NewProject);
        panel_NewProject.setLayout(panel_NewProjectLayout);
        panel_NewProjectLayout.setHorizontalGroup(
            panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_NewProjectLayout.createSequentialGroup()
                        .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(label_Title))
                            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label_Comments))
                            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(panel_NewProjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                                .addComponent(label_CreatorName)
                                .addGap(60, 60, 60)
                                .addComponent(textField_CreatorName))
                            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                                .addComponent(label_ProjectName)
                                .addGap(23, 23, 23)
                                .addComponent(textField_ProjectName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_NewProjectLayout.createSequentialGroup()
                                .addComponent(label_ProductName)
                                .addGap(18, 18, 18)
                                .addComponent(textField_ProductName))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        panel_NewProjectLayout.setVerticalGroup(
            panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NewProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ProjectName)
                    .addComponent(textField_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ProductName)
                    .addComponent(textField_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_CreatorName)
                    .addComponent(textField_CreatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(label_Comments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_OK)
                    .addComponent(button_Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_NewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_NewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_OKMouseClicked
        //Only create project if project name is filled in
        if(!textField_ProjectName.getText().isEmpty()) {
            mainFrame.setProjectName(textField_ProjectName.getText());
            mainFrame.setProductName(textField_ProductName.getText());
            mainFrame.setCreatorName(textField_CreatorName.getText());
            mainFrame.setComments(textPane_Comments.getText());
            mainFrame.enableMenu();
            DefaultMutableTreeNode selectedNode = mainFrame.getTreeNode();
            selectedNode = (DefaultMutableTreeNode)mainFrame.getRootNode();
            if(selectedNode != null) {
                System.out.println(textField_ProjectName.getText());
                selectedNode.add(new DefaultMutableTreeNode(textField_ProjectName.getText()));
                mainFrame.getModel().reload(selectedNode);
            }
            this.dispose();
        }
    }//GEN-LAST:event_button_OKMouseClicked

    private void button_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_CancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_button_CancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cancel;
    private javax.swing.JButton button_OK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Comments;
    private javax.swing.JLabel label_CreatorName;
    private javax.swing.JLabel label_ProductName;
    private javax.swing.JLabel label_ProjectName;
    private javax.swing.JLabel label_Title;
    private javax.swing.JPanel panel_NewProject;
    private javax.swing.JTextField textField_CreatorName;
    private javax.swing.JTextField textField_ProductName;
    private javax.swing.JTextField textField_ProjectName;
    private javax.swing.JTextPane textPane_Comments;
    // End of variables declaration//GEN-END:variables
}
