/**
 * File: Save.java
 * Author: Steven Phung
 * Class: CECS-543-01 - Advanced Software Engineering
 * 
 * Assignment: Semester Project v.1.0
 * Date last modified: 2/24/2021
 * 
 * Purpose: This is the class that saves the project as an .ms file.
 */
package cecs_543_semester_project;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Save extends javax.swing.JFrame {
    
    //Parent class.
    private MainFrame mf;
    //Save data.
    private String[] info;
    //userSelection tracks whether user clicked open or cancel in dialog.
    private int userSelection;
    
    public Save(MainFrame mf, String[] info) {
        initComponents();
        this.mf = mf;
        this.info = info;
        initDefaultFileToSave();
        setDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFileChooser2 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser2.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser2.setDialogTitle("Save File");
        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        //User clicks save
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = jFileChooser2.getSelectedFile();
            try {
                FileWriter out;
                //If file to be saved does not end in .ms, add .ms to it.
                if(!fileToSave.getAbsolutePath().endsWith(".ms")) {
                    out = new FileWriter(fileToSave.getAbsolutePath() + ".ms");
                } else {
                    out = new FileWriter(fileToSave.getAbsolutePath());
                }
                //Write data to the file
                for (String info1 : info) {
                    //System.out.println(info1);
                    out.write(info1 + "\n");
                }
                out.close();
            } catch(IOException | NullPointerException e) {
                this.dispose();
            }
        }
        //User clicks cancel
        if (userSelection == JFileChooser.CANCEL_OPTION) {
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    //Method: setDialog()
    //Show "save" dialog for saving files and get userSelection.
    private void setDialog() {
        userSelection = jFileChooser2.showSaveDialog(this);
    }
    
    //Method: initDefaultFileToSave()
    //Default dialog view options to certain files and home directory.
    private void initDefaultFileToSave() {
        //Set default file name to be saved based on project name.
        jFileChooser2.setSelectedFile(new File(mf.getProjectName() + ".ms"));
        //Set an extension filter
        jFileChooser2.setFileFilter(new FileNameExtensionFilter(".ms file","ms"));
        //Set default directory to user home
        jFileChooser2.setCurrentDirectory(new File(System.getProperty("user.home")));

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
